## Task 1: Numerical Transformation Using List Data Structure


In [ ]:
numbers = [1,2,3,4,5,6,7,8,9]

evenSquared=[]   
oddCubed=[] 

for num in numbers:
    if num%2==0:
        evenSquared.append(num**2)
    else:
        oddCubed.append(num**3)
        
print("squared even numbers:",evenSquared)
print("cubed odd numbers:",oddCubed)

merged_sorted_list = sorted(evenSquared+oddCubed)

print("merged and sorted list:",merged_sorted_list)


squared even numberss: [4, 16, 36, 64]
cubed odd numbers: [1, 27, 125, 343, 729]
merged and sorted list: [1, 4, 16, 27, 36, 64, 125, 343, 729]


## Task 2: Dictionary-Based Information Mapping and Ranking


In [1]:
entities = {}

entities[1] = {"name": "A", "category": "X", "value": 75}
entities[2] = {"name": "B", "category": "Y", "value": 40}
entities[3] = {"name": "C", "category": "X", "value": 90}
entities[4] = {"name": "D", "category": "Z", "value": 60}
entities[5] = {"name": "E", "category": "Y", "value": 30}

values = {k: v["value"] for k, v in entities.items()}

max_ent = max(values, key=values.get)

print("Max:", entities[
max_ent  ])

min_ent = min(values, key=values.get)

print("Min:", entities[

min_ent  ])

sorted_entities = sorted(entities.items(),key=lambda item:item[1]["value"])

print("all entities sorted byy value:")
for key, entity in sorted_entities:
    print(entity)

Max: {'name': 'C', 'category': 'X', 'value': 90}
Min: {'name': 'E', 'category': 'Y', 'value': 30}
all entities sorted byy value:
{'name': 'E', 'category': 'Y', 'value': 30}
{'name': 'B', 'category': 'Y', 'value': 40}
{'name': 'D', 'category': 'Z', 'value': 60}
{'name': 'A', 'category': 'X', 'value': 75}
{'name': 'C', 'category': 'X', 'value': 90}


# Task 3: Functional Programming and Lambda-Based Data Normalization

In [10]:
data = [5,10,20,100,25,8,80]

print(f"original data: {data}")

get_abs_diff = lambda x, y: abs(x - y)
normalize_logic = lambda x, minVal, maxVal: (x - minVal) / (maxVal - minVal)

clean_data = list(filter(lambda x: x > 10, data))
print(f"filtered data (values>10): {clean_data}")

data_min = min(clean_data)
data_max = max(clean_data)

normalized_data = list(map(lambda x: normalize_logic(x, data_min, data_max), clean_data))

print("\nnormalized data (between 0 and 1):")
print(normalized_data)

print(f"min: {min(normalized_data)}, max: {max(normalized_data)}")


original data: [5, 10, 20, 100, 25, 8, 80]
filtered data (values>10): [20, 100, 25, 80]

normalized data (between 0 and 1):
[0.0, 1.0, 0.0625, 0.75]
min: 0.0, max: 1.0


# Task 4: Multi-Dimensional Data Representation Using NumPy

In [10]:
import numpy as np

matrix = np.random.randint(0, 100, size=(6, 4))
print("matrix:")
print(matrix)

print("\nmatrix shape:", matrix.shape)
print("matrix size:", matrix.size)
print("matrix data type:", matrix.dtype)

column_mean = np.mean(matrix, axis=0)
print("\ncolumn-wise mean:")
print(column_mean)

row_max = np.max(matrix, axis=1)
print("\nrow-wise maximum:")
print(row_max)

max_index = np.argmax(matrix)
print("\nindex of maximum element in matrix:")
print(max_index)


matrix:
[[23 87 17  6]
 [71 67  9 58]
 [87 82 38 22]
 [96 90 34 60]
 [ 1  5 76 51]
 [87 54 17 81]]

matrix shape: (6, 4)
matrix size: 24
matrix data type: int64

column-wise mean:
[60.83333333 64.16666667 31.83333333 46.33333333]

row-wise maximum:
[87 71 87 96 76 87]

index of maximum element in matrix:
12


# Task 5: Data Ranking and Comparative Analysis Using NumPy

In [ ]:

import numpy as np

scores = np.array([
    [80, 85, 78],
    [90, 88, 92],
    [70, 75, 72]
])

average_scores = np.mean(scores, axis=1)
print("average score per system:")
print(average_scores)

ranking = np.argsort(average_scores)[::-1]

print("\nsystem ranking (best to worst):")
for rank in ranking:
    print(f"system {rank + 1} with average score {average_scores[rank]}")


average score per system:
[81.         90.         72.33333333]

system ranking best to worst):
system 2 with average score 90.0
system 1 with average score 81.0
system 3 with average score 72.33333333333333


# Task 6

In [ ]:
import numpy as np

data = np.random.rand(100, 3)
print("original data shape:", data.shape)

data_min = np.min(data, axis=0)
data_max = np.max(data, axis=0)

normalized_data = (data - data_min) / (data_max - data_min)

variance = np.std(normalized_data, axis=0)
highest_variance_column = np.argmax(variance)

row_sums = np.sum(normalized_data, axis=1)
max_sum_row = np.argmax(row_sums)

print("\ncolumn-wise variance:")
print(variance)
print("column with highest variance:", highest_variance_column)

print("\nrow with maximum total value:", max_sum_row)


original data shape: (100, 3)

column-wise variance:
[0.2893591  0.27920132 0.29620184]
column with highest variance: 2

row with maximum total value: 62
